{
  imports = [
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./env.nix
    ./flatpak.nix
    ./home-manager.nix
    ./hyprland.nix
    ./net.nix
    ./nh.nix
    ./nix.nix
    ./timezone.nix
    ./user.nix
    ./ssh.nix
    ./printing.nix
    ./trackpad.nix
    ./virtualisation.nix
    ./tailscale.nix
  ];
}
